module.exports = [
  'All UI/UX team members confirmed to basic understanding, and agreed upon the benefits of best practices using USM on `StoriesOnBoard` groupware for product design and development.',
  'The go/no-go decision for Bridges-FE initiative will be agreed upon coming final LLD conversations, 1/11/2018, and for the completion of logistics on the StoriesOnBoard housekeeping, and upcoming HLD/LLD discussions.',
  'Going forward on SASS structure at global/common singleton directive directory services',
  'The mobile-first approach is equivalent to progressive enhancement for media queries aiming particular screen resolutions or orientations for example. ',
  'In terms of...SASS',
  'Regards to SASS, should consider SASS-Compass library and tool for build image/icon UI Sprites with low learning curve.',
  'As for linting and debugging purposes, we can install JSHint v.2.9.5, and use it from CLI manually, until we can fine tune the webpack-castlebranch SDLC workflow automation.',
  'This is what we\'ll need to have a list for our Domain Data Models and Named Scopes.',
  'We talk about Mock up for our UI/UX design. You can download this Axure RP8 for 30 days trail. I am sure you are aware this software for wireframing! Let me have your thoughts!',
  'We have no tee QUACK',
  'You know what PHP stands for? Patch. Hack. And...PATCH',
  'You know what PHP stands for? Patch. Hack. And...PACK',
  'These God Damn backend developers',
  '*pretends to type on keyboard*',
  'My understanding is that we\'ve designed and developed a real-time web application for ourselves (Users) in terms of how to navigate, activate and communicate allowing the separation of cross-cutting concerns.',
  'Obviously, it\'s all about an abstraction to communication, coordination and collaboration of UX/UI team efforts to implementation.',
  'To confirm, this USM production is not a frivolous, but a simply value-added work of the Solutions Architect for UX/UI Team at CastleBranch to balance and resolve the recurring issues pertaining to design, development, and programming patterns for CB Bridges software/application and beyond.',
  'Protractor',
  'What\'s your story? *smirks*',
  'We\'re talking about the stories of CB Bridges now, and  to later for Bridges-FE mobile first responsive web design single page application coupling with Vue JS 2 architecture.',
  'Jitlab',
  '*uploads PowerPoint to repo*',
  'Almost, absolute concern of mine is to coach and knowledge sharing on product design, develop and programming;  also to better serve for UX/UI team\'s advantage. That\'s It!',
  'Roger. Over and out.',
  'She\'s too inexperience to understand conception. I may have to put her in observer status.',
  'In terms of... *coughs*',
  'it all depends on how you design the data models in JavaScript Object Literals and Array. You may adhere to the Flux Architecture to drive your context and scope anyway, as long as we are aware of JavaScript prototypical inheritance paradigm.',
  'Yes, we still need to be aware of the Laravel\'s Twitter Bootstrap CSS Framework. Our required Blade templates are tightly coupled, and be aware of the class explosion for style guides and conventions!',
  'This is quite innovative and sophisticated but quite helpful and simulating. How about time consumption and on iteration on changes?',
  'We have faced SCSS/CSS files that previous "designers" wrote and that mutated into a huge sprawling, incoherent mess being applied to current client-facing CB Bridges application. We have looked the beast in the eye and barely survived.',
  'To remedy this problem, the UI/UX team have started with new redesign on layouts, topography, imagery, iconography and relevant UI states on applying to CB Bridges\'s features and functionality.',
  'In terms of... iconography',
  'Need to cut that CRAP!',
  'BYOP. Bring your own...PRODUCT *he hehe he* I used to work for tracphones *he he* and they would say BYOP.',
  '@aaron wilson @Dillon @Travis Ray @Eric Guys! I have your RSVPed PPM complaints. We need to rocket chat in reality and on real-time. We need to deliver this PPM product to JR/TH clients. I spent the whole weekend to get your scripts done. Tomorrow, 1/22/2018 is the deadline, so Roger! We have a problem. We need to get this done. You all said that your shared understanding for your separation of concerns.  Therefore, I am going to issue RTFM tickets. The charges...two has Drank UI too much and the other charges are on dope and flying high with LSD watching uXxx. I have a bigger problem, because, I was on both UI/UX, also with USM on the SOB telling about BYOP trip.We are all guilty but need to plea NOT GUILTY (ABLE WAS I SAW ELBA). Let\'s all get on-board before going to court at real Rocket Chat root room castlebranch. I need to see all of you with your complaints and the tickets by 10 am sharp. This is my experience real (not fake) story mapping  works in real time. If we plea NOT guilty, then we need to deliver this PPM product by before noon, the latest COB 1.22.2018 (localized). Adios Amigos...Mañana UI/UX Team!',
  'My primary concern is the timing on the production of the product/feature/functionality and/or materials for the UX/UI CB Bridges, in our use case - The Right Product Right on Time. The purpose and reason behind should satisfy the outcome or have impact on the valued product.',
  'We had shared understanding of cross-functional UX/UI coverage at and/or between the User Engagement/Service Orchestration layers.',
  'No worries! SB is off-boarded because her unit test case proved TRUE.  I need this e2e testing is valid. I need all of you to prove this test suite is correct thanks mates, Cheers!',
  'As well as you have your say on these "Agile/Scrum/Sprint" cards. Any Questions?',
  'The USM workshop for UI/UX Team has been sign-off as of 1/18/2018. No minutes on UI/UX Team update for this final session will be followed. In fact, the team considered we got the "The Right Product" USM on this outcome. Thank you, Stephen, Solutions Architect@castlebranch. "What Your Story?"',
  'It\'s boarding time for VI. JSON Schema API & CouchDB Services user story map Please checkout your boarding (pass) cards on The Right Product Story Map\'s online discussion board.',
  'BTW, Travis, you don\'t want to miss the flight like yesterday, otherwise, you\'ll be left behind with invalid RTFM boarding (pass) card. Last chance?',
  'Dillon, Shanade, and Eric (no worries about DUI). Aaron has been already given a notification alert!',
  'Almost, absolute concern of mine is to coach and knowledge sharing on product design, develop and programming;  also to better serve for UX/UI team\'s advantage. That\'s It! Happy New Year to you all.',
  'To design a responsive layout, we can forget about the usual static 960px width layouts and go fluid with percentage width and media queries. That is Bridges FE is based on 994px Responsive Web Design.',
  'As for inclusion of hiDPI images for the CB branding and theming, all images will be sized to width for the unit of measurements in percentages.',
  'The mobile-first approach is equivalent to progressive enhancement for media queries aiming particular screen resolutions or orientations for example. The design principle is to get started with the lowest resolution devices, and then enhance the experience for larger or bigger screens or viewports.',
  'I have just shared the workflow automation documents with the team for both JS and CSS linting options on the development and production flow as following CONTRIBUTION.md, gulpfile.js, and package.json',
  'Out of the context, out of the scope, I cannot function.',
  'I\'m not touching it',
  'Bleep Bleep Bleep....BLEEP',
  'Like a clown, like a joker, in a circus.',
]